# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_survey_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='use_anonymized_hashing',
            field=models.BooleanField(default=False),
        ),
    ]
