# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_devicesettings_use_anonymized_hashing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkregistry',
            name='chunk_path',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='data_type',
            field=models.CharField(choices=[(b'accelerometer', b'accelerometer'), (b'bluetooth', b'bluetooth'), (b'calls', b'calls'), (b'gps', b'gps'), (b'identifiers', b'identifiers'), (b'app_log', b'app_log'), (b'power_state', b'power_state'), (b'survey_answers', b'survey_answers'), (b'survey_timings', b'survey_timings'), (b'texts', b'texts'), (b'audio_recordings', b'audio_recordings'), (b'wifi', b'wifi'), (b'proximity', b'proximity'), (b'gyro', b'gyro'), (b'magnetometer', b'magnetometer'), (b'devicemotion', b'devicemotion'), (b'reachability', b'reachability'), (b'ios_log', b'ios_log'), (b'image_survey', b'image_survey')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='time_bin',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lineencryptionerror',
            name='type',
            field=models.CharField(choices=[(b'AES_KEY_BAD_LENGTH', b'AES_KEY_BAD_LENGTH'), (b'EMPTY_KEY', b'EMPTY_KEY'), (b'INVALID_LENGTH', b'INVALID_LENGTH'), (b'IV_BAD_LENGTH', b'IV_BAD_LENGTH'), (b'IV_MISSING', b'IV_MISSING'), (b'LINE_EMPTY', b'LINE_EMPTY'), (b'LINE_IS_NONE', b'LINE_IS_NONE'), (b'MP4_PADDING', b'MP4_PADDING'), (b'MALFORMED_CONFIG', b'MALFORMED_CONFIG'), (b'PADDING_ERROR', b'PADDING_ERROR')], max_length=32),
        ),
    ]
