# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180523_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesettings',
            name='use_anonymized_hashing',
            field=models.BooleanField(default=True),
        ),
    ]
