# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-30 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20180525_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptionerrormetadata',
            old_name='errors_lines',
            new_name='error_lines',
        ),
        migrations.AddField(
            model_name='decryptionkeyerror',
            name='traceback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='encryptionerrormetadata',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Participant'),
        ),
        migrations.AddField(
            model_name='lineencryptionerror',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.Participant'),
        ),
    ]
