# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-12 02:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_participantaliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantaliases',
            name='alias_id',
            field=models.CharField(help_text=b'Eight-character unique ID with characters chosen from 1-9 and a-z', max_length=8, validators=[django.core.validators.RegexValidator(b'^[1-9a-z]+$', message=b'This field can only contain characters 1-9 and a-z.')]),
        ),
        migrations.AlterField(
            model_name='participantaliases',
            name='reference_id',
            field=models.CharField(help_text=b'Eight-character unique ID with characters chosen from 1-9 and a-z', max_length=8, validators=[django.core.validators.RegexValidator(b'^[1-9a-z]+$', message=b'This field can only contain characters 1-9 and a-z.')]),
        ),
    ]
