# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20190112_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedDataStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(max_length=256)),
                ('last_upload_timestamp', models.DateTimeField()),
                ('number_of_uploads', models.PositiveIntegerField()),
                ('number_bytes_uploaded', models.PositiveIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_data_stats', to='database.Participant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='receiveddatastats',
            unique_together=set([('participant', 'data_type')]),
        ),
    ]
