# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-13 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20190113_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveddatastats',
            name='number_bytes_uploaded',
            field=models.BigIntegerField(),
        ),
    ]
