# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-15 18:48
from __future__ import unicode_literals

import database.common_models
import database.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20190113_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content', database.common_models.JSONTextField(default='[]', help_text='JSON blob containing information about the survey questions.')),
                ('survey_type', models.CharField(choices=[('audio_survey', 'audio_survey'), ('tracking_survey', 'tracking_survey'), ('dummy', 'dummy'), ('image_survey', 'image_survey')], help_text='What type of survey this is.', max_length=16)),
                ('settings', database.common_models.JSONTextField(default='{}', help_text='JSON blob containing settings for the survey.')),
                ('timings', database.common_models.JSONTextField(default=b'[[], [], [], [], [], [], []]', help_text='JSON blob containing the times at which the survey is sent.')),
                ('object_id', models.CharField(max_length=24, unique=True, validators=[database.validators.LengthValidator(24)])),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_surveys', to='database.Participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_surveys', to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
