# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-15 19:03
from __future__ import unicode_literals

from django.db import migrations

def survey_names(apps, schema_editor):

    Survey = apps.get_model('database', 'Survey')
    for survey in Survey.objects.all():
        survey.name = "Study survey {}".format(survey.object_id)
        survey.save()
    
    SurveyArchive = apps.get_model('database', 'SurveyArchive')
    for survey in SurveyArchive.objects.all():
        survey.name = "Archived study survey {}".format(survey.survey.object_id)
        survey.save()

    ParticipantSurvey = apps.get_model('database', 'ParticipantSurvey')
    for survey in ParticipantSurvey.objects.all():
        survey.name = "Participant survey {}".format(survey.object_id)
        survey.save()


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20190115_1901'),
    ]

    operations = [
        migrations.RunPython(survey_names),
    ]
