# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-15 22:44
from __future__ import unicode_literals

from django.db import migrations

def survey_archive_unique_name(apps, schema_editor):
    SurveyArchive = apps.get_model('database', 'SurveyArchive')
    for survey in SurveyArchive.objects.all():
        survey.name = "Archived study survey {} {}".format(survey.survey.object_id, survey.archive_end.isoformat())
        survey.save()

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20190115_1903'),
    ]

    operations = [
        migrations.RunPython(survey_archive_unique_name),
    ]
