# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20190115_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedDataStatsHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(max_length=256)),
                ('data_collection_hour', models.DateTimeField()),
                ('number_of_observations', models.PositiveIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_data_stats_hourly', to='database.Participant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='receiveddatastatshourly',
            unique_together=set([('participant', 'data_type', 'data_collection_hour')]),
        ),
    ]
