# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20190802_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecutionTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pipeline_submission_timestamp', models.DateTimeField()),
                ('email_address_list', models.CharField(max_length=256)),
                ('query_start_datetime', models.DateTimeField()),
                ('query_end_datetime', models.DateTimeField()),
                ('participants', models.CharField(max_length=256)),
                ('execution_status', models.CharField(max_length=256)),
                ('execution_error_text', models.TextField()),
                ('execution_start_datetime', models.DateTimeField()),
                ('execution_end_datetime', models.DateTimeField()),
                ('execution_time_minutes', models.FloatField()),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='researcher_pipelines', to='database.Researcher')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_pipelines', to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
