# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_pipelineexecutiontracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='email_address_list',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='execution_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='execution_error_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='execution_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='execution_time_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='participants',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='query_end_datetime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecutiontracking',
            name='query_start_datetime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
