# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20190802_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecutiontracking',
            name='batch_job_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
