# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-11 06:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_pipelineexecutiontracking_batch_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('study_configuration', django.contrib.postgres.fields.jsonb.JSONField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='data_type',
            field=models.CharField(choices=[(b'accelerometer', b'accelerometer'), (b'bluetooth', b'bluetooth'), (b'calls', b'calls'), (b'gps', b'gps'), (b'identifiers', b'identifiers'), (b'app_log', b'app_log'), (b'power_state', b'power_state'), (b'survey_answers', b'survey_answers'), (b'survey_timings', b'survey_timings'), (b'texts', b'texts'), (b'audio_recording', b'audio_recording'), (b'wifi', b'wifi'), (b'proximity', b'proximity'), (b'gyro', b'gyro'), (b'magnetometer', b'magnetometer'), (b'devicemotion', b'devicemotion'), (b'reachability', b'reachability'), (b'ios_log', b'ios_log'), (b'image_survey', b'image_survey')], db_index=True, max_length=32),
        ),
    ]
