# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20191211_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkregistry',
            name='number_of_observations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
