# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-12 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_chunkregistry_number_of_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardColorSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(max_length=32)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_colors', to='database.Study')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardGradient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('color_range_min', models.IntegerField(default=0)),
                ('color_range_max', models.IntegerField(default=0)),
                ('dashboard_color_setting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gradient', to='database.DashboardColorSetting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardInflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(max_length=1)),
                ('inflection_point', models.IntegerField(default=0)),
                ('dashboard_color_setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflections', to='database.DashboardColorSetting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(db_index=True, max_length=256)),
                ('processed_data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True)),
                ('uploaded_at', models.DateTimeField(db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_registries', to='database.Participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_registries', to='database.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='chunkregistry',
            name='data_type',
            field=models.CharField(choices=[(b'accelerometer', b'accelerometer'), (b'bluetooth', b'bluetooth'), (b'calls', b'calls'), (b'gps', b'gps'), (b'identifiers', b'identifiers'), (b'app_log', b'app_log'), (b'power_state', b'power_state'), (b'survey_answers', b'survey_answers'), (b'survey_timings', b'survey_timings'), (b'texts', b'texts'), (b'audio_recordings', b'audio_recordings'), (b'wifi', b'wifi'), (b'proximity', b'proximity'), (b'gyro', b'gyro'), (b'magnetometer', b'magnetometer'), (b'devicemotion', b'devicemotion'), (b'reachability', b'reachability'), (b'ios_log', b'ios_log'), (b'image_survey', b'image_survey')], db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardcolorsetting',
            unique_together=set([('data_type', 'study')]),
        ),
    ]
