# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-12 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20191212_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(db_index=True, max_length=32)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_relations', to='database.Researcher')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_relations', to='database.Study')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studyrelation',
            unique_together=set([('study', 'researcher')]),
        ),
    ]
