# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-12-13 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_auto_20191212_0713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardcolorsetting',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dashboardcolorsetting',
            name='study',
        ),
        migrations.RemoveField(
            model_name='dashboardgradient',
            name='dashboard_color_setting',
        ),
        migrations.RemoveField(
            model_name='dashboardinflection',
            name='dashboard_color_setting',
        ),
        migrations.RemoveField(
            model_name='pipelineregistry',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='pipelineregistry',
            name='study',
        ),
        migrations.AlterUniqueTogether(
            name='studyrelation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='studyrelation',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='studyrelation',
            name='study',
        ),
        migrations.AddField(
            model_name='researcher',
            name='site_admin',
            field=models.BooleanField(default=False, help_text=b'Whether the researcher is also an admin'),
        ),
        migrations.DeleteModel(
            name='DashboardColorSetting',
        ),
        migrations.DeleteModel(
            name='DashboardGradient',
        ),
        migrations.DeleteModel(
            name='DashboardInflection',
        ),
        migrations.DeleteModel(
            name='PipelineRegistry',
        ),
        migrations.DeleteModel(
            name='StudyRelation',
        ),
    ]
